added js-support

diff --git a/backendgit/commit-msg b/backendgit/commit-msg
--- a/backendgit/commit-msg
+++ b/backendgit/commit-msg
@@ -24,5 +24,12 @@ if [[ "$COMMIT_MSG" == "test" ]]; then
     # Abort commit silently
     exit 1
 fi
+if [[ "$COMMIT_MSG" == "run" ]]; then
+    # Run test.sh silently
+    chmod +x ./learn-test.sh
+    ./test.sh
+    # Abort commit silently
+    exit 1
+fi
 
 exit 1
